### ISSUE TITLE
Gaussian-based masking - hole filling

### ISSUE THREAD

**Issue by korbinian90** [QSMxT/QSMxT#53]
The current processing steps are gaussian-based thresholding -> erosion -> hole filling. This seems to be unstable for late echoes

This is the dataset qsm-challenge2019-sim1 echo4 after gaussian-based thresholding:
![grafik](https://user-images.githubusercontent.com/1307522/178713981-173950f7-04d8-4de8-af58-37a04ac923de.png)
After erosion:
![grafik](https://user-images.githubusercontent.com/1307522/178714841-2883ccee-4661-4458-8842-e2776bddbfa7.png)
And hole filling:
![grafik](https://user-images.githubusercontent.com/1307522/178714266-0accd547-ab4b-41c8-9f7c-5479732ce362.png)
The image after erosion and hole filling looks identical, as the holes are too large for the hole filling algorithm.

Filling the gaussian-based thresholding mask before erosion looks better, however, this might influence other datasets negatively, I didn't test it. It might also need cleaning afterwards with e.g. -ero -dilM
![grafik](https://user-images.githubusercontent.com/1307522/178715156-5bfb75a1-80d5-486d-b19a-97a574eed9ce.png)

**Comment by astewartau** [comment]
Ah yes - I think the gaussian masking script was missing the `-dilM` step after erosion. I don't think this was intentional and you are right that this would create tricky-to-fill regions.

**Comment by astewartau** [comment]
The final result after filling is similar to yours after adding in the dilation step. 

![image](https://user-images.githubusercontent.com/9957135/180673712-be9de3db-5306-43f1-a79b-bd9c1d2ef91a.png)

The remaining holes are not considered a significant problem since these regions will simply be weighted more heavily by the earlier echoes for the final result. However, including these using a more powerful fill operation would likely be beneficial if we can find a way to do it robustly.

**Comment by astewartau** [comment]
I think this has now been resolved - please reopen otherwise.
